server:
  port: 8082
  servlet:
    context-path: /martiastrid
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/martiastrid_pizza?user=app&currentSchema=pizza
    password: app
  jpa:
    database: postgresql
    show-sql: true
